services:
    watchtower:
        image: containrrr/watchtower:latest
        environment:
            - WATCHTOWER_POLL_INTERVAL=60
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower

    node-app:
        image: sakuheinonen/node-app:latest
        ports:
            - "8080:8080"
        container_name: node-app
