name: Release Node.js app

on:
    push:
        branches:
            - main
        paths:
            - "index.js"
            - "Dockerfile"
            - "package.json"
            - ".github/workflows/main.yaml"
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  platforms: linux/amd64,linux/arm64
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/node-app:latest
